---
# Download images if download url is defined
- name: Download virtual backgrounds
  get_url:
    url: "{{ bbb_vb_download_url | regex_replace('\\/$', '')}}/{{ item }}"
    dest: "/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ bbb_virtual_backgrounds }}"
  when: bbb_vb_download_url is defined

# Use images provided outside of the role
- name: Copy virtual backgrounds to the bbb node
  copy:
    src: "{{ bbb_virtual_background_path | regex_replace('\\/$', '') }}/{{ item }}"
    dest: "/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ bbb_virtual_backgrounds }}"
  when: bbb_vb_download_url is not defined

- name: Optimize jpegs
  when: bbb_jpeg_optimization | bool
  block:
    - name: Install jpegoptim
      apt:
        package: jpegoptim
        update_cache: true

    - name: Optimze vb
      command: jpegoptim /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/* .jpg --strip-all

- name: Copy shell script for creation of thumbnails
  copy:
    src: vb-thumbnail.sh
    dest: /root/vb-thumbnail.sh
    mode: 0700
    owner: root
    group: root

- name: Create thumbnails
  command: '/root/vb-thumbnail.sh'

- name: Remove thumbnail script
  file:
    path: /root/vb-thumbnail.sh
    state: absent

- name: Add config for vb to html config
  become: true
  blockinfile:
    path: /etc/bigbluebutton/bbb-html5.yml
    marker_begin: "begin virtual backgrounds"
    marker_end: "end virtual background"
    insertafter: "public:"
    block: |2
        virtualBackgrounds:
          fileNames:
          {% for item in bbb_virtual_backgrounds -%}
            - "{{ item }}"
          {% endfor -%}
  notify:
    - restart bbb-html5