---
# Download images if download url is defined
- name: Download virtual backgrounds
  get_url:
    url: "{{ bbb_vb_download_url | regex_replace('\\/$', '')}}/{{ item }}"
    dest: "/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ bbb_meteor.public.virtualBackgrounds.fileNames }}"
  when: bbb_vb_download_url is defined

# Use images provided outside of the role
- name: Copy virtual backgrounds to the bbb node
  copy:
    src: "{{ bbb_virtual_background_path | regex_replace('\\/$', '') }}/{{ item }}"
    dest: "/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ bbb_meteor.public.virtualBackgrounds.fileNames }}"
  when: bbb_vb_download_url is not defined

- name: Optimize jpegs
  when: bbb_jpeg_optimization | bool
  block:
    - name: Install jpegoptim
      apt:
        package: jpegoptim
        update_cache: true

    - name: Optimze vb
      command: jpegoptim /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/* .jpg --strip-all

- name: create thumbnails
  command: convert /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/"{{ item }}" -resize 50x50^ -gravity Center -extent 50x50 "/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/thumbnails/"{{ item }}""
  with_items: "{{ bbb_meteor.public.virtualBackgrounds.fileNames }}"
